version: '3'

services: 
  backend:
    build:
      context: WebServer/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on: 
      - db

  db:
    container_name: mysql
    image: mysql:5.7.25
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: modular
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports: 
      - 3306:3306
    